name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0' 
        
    - name: Build
      run: make 

    - name: Clean
      run: make clean

